# Generated by Django 5.1.1 on 2024-09-29 12:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_description_alter_todo_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('objects_done', django.db.models.manager.Manager()),
            ],
        ),
    ]
