# Generated by Django 5.1.1 on 2024-09-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
            ],
        ),
    ]
