# Generated by Django 5.1.1 on 2024-10-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_done', '-pub_date']},
        ),
    ]
